apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orchestra-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "namespaces"]
    verbs: ["get", "list"]
