apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orchestra-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: orchestra-sa
    namespace: orchestra
roleRef:
  kind: ClusterRole
  name: orchestra-clusterrole
  apiGroup: rbac.authorization.k8s.io
