apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestra
  namespace: orchestra
  labels:
    app: orchestra
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: orchestra
  template:
    metadata:
      labels:
        app: orchestra
    spec:
      serviceAccountName: orchestra-sa
      containers:
        - name: orchestra
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 8000
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
