apiVersion: v1
kind: Service
metadata:
  name: orchestra
  namespace: orchestra
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: orchestra
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.backend.service.port }}